#!/usr/bin/env -S uv --quiet run --script

# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "asyncclick",
#     "mcp[cli]>=1.8.0",
# ]
# ///
# ::: Code Generated by Copilot [7f5f8ff2-6e8b-4e2a-9f70-1ad5baf7c2d1]. This comment will be removed automatically after the file is saved :::
"""
check_links.py — validate internal links inside changed ES Markdown files.

Checks:
  - Markdown links [text](path) and [text](path#anchor)
  - Hugo relref shortcodes  {{< relref "path" >}}  and  {{< relref "path#anchor" >}}
  - Anchor existence inside target files

Outputs:
{
  "findings": [...],
  "errors": [["file", "msg"]]
}
"""

import argparse
import json
import re
import urllib.parse
from pathlib import Path

CONTEXT_RADIUS = 2


def make_context_window(lines: list[str], line_no: int, radius: int = CONTEXT_RADIUS) -> dict:
    start = max(1, line_no - radius)
    end = min(len(lines), line_no + radius)
    return {
        "line_text": lines[line_no - 1].rstrip(),
        "context_before": [
            {"line": idx, "text": lines[idx - 1].rstrip()}
            for idx in range(start, line_no)
        ],
        "context_after": [
            {"line": idx, "text": lines[idx - 1].rstrip()}
            for idx in range(line_no + 1, end + 1)
        ],
    }

# Hugo content root candidates to resolve absolute paths
CONTENT_ROOT_CANDIDATES = ["content/es", "content/en", "content"]

# Patterns to extract links
_MD_LINK = re.compile(r"\[(?:[^\]]*)\]\(([^)]+)\)")
_RELREF = re.compile(r'\{\{[<{]\s*relref\s+"([^"]+)"\s*[>}]\}\}')
_REF_SHORTCODE = re.compile(r'\{\{[<{]\s*ref\s+"([^"]+)"\s*[>}]\}\}')


def iter_links(text: str) -> list[tuple[int, str]]:
    """Return (line_number, raw_link) pairs for all links in text."""
    results = []
    for i, line in enumerate(text.splitlines(), 1):
        for m in _MD_LINK.finditer(line):
            raw = (
                m.group(1).split(" ")[0].strip()
            )  # strip title from [text](url "title")
            results.append((i, raw))
        for pattern in (_RELREF, _REF_SHORTCODE):
            for m in pattern.finditer(line):
                results.append((i, m.group(1).strip()))
    return results


def is_external(link: str) -> bool:
    return (
        link.startswith("http://")
        or link.startswith("https://")
        or link.startswith("//")
    )


def is_fragment_only(link: str) -> bool:
    return link.startswith("#")


def extract_heading_slugs(text: str) -> set[str]:
    """Return the set of heading anchor slugs (GitHub/Hugo style)."""
    slugs = set()
    for line in text.splitlines():
        m = re.match(r"^#{1,6}\s+(.*)", line)
        if m:
            heading = m.group(1).strip()
            # strip inline markup
            heading = re.sub(r"`[^`]*`", "", heading)
            heading = re.sub(r"\*+([^*]*)\*+", r"\1", heading)
            # Hugo slug: lowercase, spaces → hyphens, remove non-alphanum except hyphens
            slug = heading.lower()
            slug = re.sub(r"[^\w\s-]", "", slug)
            slug = re.sub(r"[\s_]+", "-", slug).strip("-")
            slugs.add(slug)
    return slugs


def resolve_link(
    raw: str, current_file: Path, repo: Path
) -> tuple[Path | None, str | None]:
    """
    Return (resolved_path, anchor) or (None, None) if unresolvable (external, fragment-only).
    """
    if is_external(raw) or is_fragment_only(raw):
        return None, None

    # URL-decode
    decoded = urllib.parse.unquote(raw)
    path_part, _, anchor = decoded.partition("#")
    anchor = anchor or None

    # Absolute path (starts with /) — resolve against content roots
    if path_part.startswith("/"):
        # Try with each language prefix
        for root in CONTENT_ROOT_CANDIDATES:
            candidate = repo / root / path_part.lstrip("/")
            # Hugo can resolve /docs/foo → .../docs/foo.md or .../docs/foo/_index.md
            for suffix in ["", ".md", "/index.md", "/_index.md"]:
                full = Path(str(candidate) + suffix)
                if full.exists():
                    return full, anchor
        return None, anchor  # not found

    # Relative path
    candidate = (current_file.parent / path_part).resolve()
    if candidate.exists():
        return candidate, anchor
    for suffix in [".md", "/index.md", "/_index.md"]:
        full = Path(str(candidate) + suffix)
        if full.exists():
            return full, anchor
    # Try stripping language prefix mismatch (es → en fallback for cross-links)
    return None, anchor


def check_file_links(es_rel: str, repo: Path) -> tuple[list[dict], str | None]:
    es_path = repo / es_rel
    if not es_path.exists():
        return [], f"File not found: {es_rel}"

    text = es_path.read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()
    links = iter_links(text)
    findings = []

    for line_no, raw in links:
        if is_external(raw) or is_fragment_only(raw):
            continue

        resolved, anchor = resolve_link(raw, es_path, repo)

        if resolved is None:
            # Check if there's an EN equivalent (warn, not error)
            path_part = raw.partition("#")[0]
            en_candidate = repo / "content/en" / path_part.lstrip("/")
            en_candidate_rel = None
            for suffix in ["", ".md", "/index.md", "/_index.md"]:
                candidate = Path(str(en_candidate) + suffix)
                if candidate.exists():
                    en_candidate_rel = str(candidate.relative_to(repo))
                    break
            en_exists = any(
                Path(str(en_candidate) + s).exists()
                for s in ["", ".md", "/index.md", "/_index.md"]
            )
            severity = "warning" if en_exists else "error"
            code = "LINK-002" if en_exists else "LINK-001"
            msg = (
                f"Enlace roto `{raw}`: no se encontró el archivo destino en el repositorio."
                + (" Existe una versión EN pero no ES." if en_exists else "")
            )
            findings.append(
                {
                    "file": es_rel,
                    "line": line_no,
                    "severity": severity,
                    "code": code,
                    "message": msg,
                    "suggestion": (
                        f"Actualizar el destino `{raw}` para que apunte a una ruta válida "
                        "o eliminar el enlace si ya no aplica."
                    ),
                    "reference_file": en_candidate_rel,
                    "reference_line": 1 if en_candidate_rel else None,
                    **make_context_window(lines, line_no),
                }
            )
            continue

        # Validate anchor
        if anchor:
            try:
                target_text = resolved.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue  # file exists in git index but not in sparse checkout
            slugs = extract_heading_slugs(target_text)
            if anchor not in slugs:
                findings.append(
                    {
                        "file": es_rel,
                        "line": line_no,
                        "severity": "error",
                        "code": "LINK-003",
                        "message": (
                            f"Ancla `#{anchor}` no encontrada en `{resolved.relative_to(repo)}`. "
                            f"Anclas disponibles: {', '.join(sorted(slugs)[:8]) or 'ninguna'}."
                        ),
                        "suggestion": (
                            f"Cambiar `#{anchor}` por una ancla existente en `{resolved.relative_to(repo)}` "
                            "o corregir el encabezado de destino."
                        ),
                        **make_context_window(lines, line_no),
                    }
                )

    return findings, None


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", required=True)
    parser.add_argument("--files", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    repo = Path(args.repo)
    files = [f.strip() for f in args.files.split(",") if f.strip()]

    all_findings: list[dict] = []
    errors: list[list[str]] = []

    for es_rel in files:
        findings, err = check_file_links(es_rel, repo)
        all_findings.extend(findings)
        if err:
            errors.append([es_rel, err])

    result = {"findings": all_findings, "errors": errors}
    Path(args.out).write_text(json.dumps(result, ensure_ascii=False, indent=2))
    print(f"check_links: {len(all_findings)} finding(s), {len(errors)} error(s)")


if __name__ == "__main__":
    main()
