#!/usr/bin/env -S uv --quiet run --script

# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "asyncclick",
#     "mcp[cli]>=1.8.0",
# ]
# ///
# ::: Code Generated by Copilot [7f5f8ff2-6e8b-4e2a-9f70-1ad5baf7c2d1]. This comment will be removed automatically after the file is saved :::
"""
check_style.py — Spanish writing quality checks for k8s docs.

Checks:
  STYLE-001  Untranslated English term blocks (4+ consecutive English words)
  STYLE-002  Register inconsistency (tú vs usted forms in the same file)
  STYLE-003  Terminology inconsistency (clúster vs cluster, etc.)
  STYLE-004  Common typographic errors (double spaces, missing accent on common words)
  STYLE-005  Code block content modified (command names must match EN source)
  STYLE-006  English phrases inside prose paragraphs (not in code blocks)

Outputs: {"findings": [...], "errors": [...]}
"""

import argparse
import json
import math
import re
from pathlib import Path

CONTEXT_RADIUS = 2


def context_window(prose_lines: list[tuple[int, str]], line_no: int) -> dict:
    entries = list(prose_lines)
    positions = {ln: idx for idx, (ln, _) in enumerate(entries)}
    idx = positions.get(line_no)
    if idx is None:
        return {"context_before": [], "context_after": []}
    start = max(0, idx - CONTEXT_RADIUS)
    end = min(len(entries), idx + CONTEXT_RADIUS + 1)
    before = [
        {"line": ln, "text": text.rstrip()}
        for ln, text in entries[start:idx]
    ]
    after = [
        {"line": ln, "text": text.rstrip()}
        for ln, text in entries[idx + 1 : end]
    ]
    return {"context_before": before, "context_after": after}

# ── Term consistency rules ────────────────────────────────────────────────────
# Each entry: (canonical_es, [variants_to_flag], code, severity)
TERMINOLOGY_RULES: list[tuple[str, list[str], str, str]] = [
    ("clúster", ["cluster"], "STYLE-003a", "suggestion"),
    ("contenedor", ["container"], "STYLE-003b", "suggestion"),
    ("nodo", ["node"], "STYLE-003c", "suggestion"),
    ("pod", [], "", ""),  # pod is kept as-is per k8s style guide
    ("imagen", ["image"], "STYLE-003d", "suggestion"),
    ("servicio", ["service"], "STYLE-003e", "suggestion"),
    ("despliegue", ["deployment"], "STYLE-003f", "suggestion"),
    ("espacio de nombres", ["namespace"], "STYLE-003g", "suggestion"),
    ("volumen", ["volume"], "STYLE-003h", "suggestion"),
]

# Terms that MUST NOT be translated (keep as English per k8s style guide)
KEEP_AS_ENGLISH = {
    "kubectl",
    "kubeadm",
    "kubelet",
    "etcd",
    "kube-proxy",
    "Deployment",
    "Service",
    "Pod",
    "ConfigMap",
    "Secret",
    "DaemonSet",
    "StatefulSet",
    "ReplicaSet",
    "Ingress",
    "PersistentVolume",
    "PersistentVolumeClaim",
    "CustomResourceDefinition",
    "Namespace",
}

# Regex for tú-form imperative verbs (2nd person singular informal)
TU_IMPERATIVES = re.compile(
    r"\b(ejecuta|instala|descarga|abre|crea|configura|verifica|comprueba"
    r"|actualiza|elimina|borra|edita|agrega|añade|usa|utiliza|aplica"
    r"|despliega|lista|obtén|revisa|asegúrate)\b",
    re.IGNORECASE,
)

# Regex for usted-form imperatives (formal)
USTED_IMPERATIVES = re.compile(
    r"\b(ejecute|instale|descargue|abra|cree|configure|verifique|compruebe"
    r"|actualice|elimine|borre|edite|agregue|añada|use|utilice|aplique"
    r"|despliegue|liste|obtenga|revise|asegúrese)\b",
    re.IGNORECASE,
)

# Common Spanish words used to disqualify a phrase from being "English"
_ES_STOPWORDS = frozenset(
    [
        "el",
        "la",
        "los",
        "las",
        "un",
        "una",
        "unos",
        "unas",
        "de",
        "del",
        "al",
        "en",
        "con",
        "por",
        "para",
        "sin",
        "sobre",
        "que",
        "qui",
        "como",
        "cuando",
        "donde",
        "si",
        "no",
        "se",
        "es",
        "son",
        "fue",
        "ser",
        "estar",
        "tiene",
        "tienen",
        "hay",
        "este",
        "esta",
        "estos",
        "estas",
        "ese",
        "esa",
        "esos",
        "esas",
        "cual",
        "cuales",
        "cuyo",
        "cuya",
        "quien",
        "quienes",
        "pero",
        "sino",
        "aunque",
        "porque",
        "pues",
        "ya",
        "aun",
        "muy",
        "bien",
        "mal",
        "mas",
        "menos",
        "todo",
        "toda",
        "todos",
        "cada",
        "otro",
        "otra",
        "mismo",
        "misma",
        "solo",
        "solo",
        "puede",
        "pueden",
        "debe",
        "deben",
        "tiene",
        "hacer",
        "usar",
        "ver",
        "leer",
        "revisar",
        "crear",
        "usar",
        "nueva",
        "nuevo",
        "siguiente",
        "ejemplo",
        "nota",
        "tipo",
        "lista",
        "archivo",
        "pagina",
        "nombre",
        "numero",
        "linea",
        "texto",
        "mensaje",
    ]
)
_SPANISH_CHARS = re.compile(r"[áéíóúüñÁÉÍÓÚÜÑ¡¿]")
_COMMON_ENGLISH_WORDS = frozenset(
    {
        "a",
        "about",
        "after",
        "all",
        "an",
        "and",
        "another",
        "any",
        "are",
        "as",
        "at",
        "be",
        "before",
        "between",
        "both",
        "but",
        "by",
        "can",
        "command",
        "commands",
        "content",
        "details",
        "docs",
        "edit",
        "example",
        "file",
        "files",
        "first",
        "for",
        "from",
        "good",
        "have",
        "how",
        "if",
        "in",
        "into",
        "is",
        "issue",
        "labels",
        "list",
        "make",
        "more",
        "must",
        "new",
        "not",
        "of",
        "on",
        "one",
        "only",
        "or",
        "other",
        "out",
        "overview",
        "page",
        "person",
        "please",
        "pr",
        "pull",
        "requested",
        "review",
        "reviewing",
        "section",
        "should",
        "some",
        "step",
        "that",
        "the",
        "their",
        "there",
        "these",
        "this",
        "through",
        "to",
        "use",
        "when",
        "where",
        "with",
        "without",
        "work",
        "wanted",
        "you",
        "your",
    }
)
_ENGLISH_FALSE_POSITIVE_TOKENS = frozenset(
    {
        "sig",
        "docs",
        "kubernetes",
        "github",
        "netlify",
        "slack",
        "markdown",
        "front",
        "matter",
        "pull",
        "request",
        "requests",
        "issue",
        "issues",
    }
)

# 4+ consecutive words with no Spanish markers — flag as possibly untranslated
_ENGLISH_WORD = r"[a-zA-Z]{3,}"
_ENGLISH_PHRASE = re.compile(r"(?:" + _ENGLISH_WORD + r"\s+){3,}" + _ENGLISH_WORD)


def _looks_english(phrase: str) -> bool:
    """Return True only for phrases with clear English evidence."""
    if _SPANISH_CHARS.search(phrase):
        return False
    tokens = re.findall(r"[A-Za-z][A-Za-z'-]*", phrase)
    if len(tokens) < 4:
        return False
    words_lower = [token.lower() for token in tokens]
    if set(words_lower) & _ES_STOPWORDS:
        return False

    meaningful_tokens = [
        token for token in words_lower if token not in _ENGLISH_FALSE_POSITIVE_TOKENS
    ]
    if not meaningful_tokens:
        return False

    english_hits = sum(1 for token in meaningful_tokens if token in _COMMON_ENGLISH_WORDS)
    required_hits = max(2, math.ceil(len(meaningful_tokens) * 0.4))
    return english_hits >= required_hits


# Double spaces
_DOUBLE_SPACE = re.compile(r"  +")

# Common words missing tilde (Spanish)
_MISSING_ACCENT: list[tuple[re.Pattern, str, str]] = [
    (re.compile(r"\bmas\b(?!\s+de\b)"), "más", "STYLE-004a"),
    (re.compile(r"\besta\b(?!\s+\w)"), "está", "STYLE-004b"),
    (re.compile(r"\beste\b"), "", ""),  # skip: too many false positives
    (re.compile(r"\btu\b(?!\s+\w)"), "tú/tu", "STYLE-004d"),
    (re.compile(r"\bel\b(?!\s+\w)"), "", ""),  # skip: too many false positives
    (re.compile(r"\bsi\b(?!\s*\()"), "", ""),  # skip
    (re.compile(r"\bpara\b"), "", ""),  # skip
    (re.compile(r"\bademas\b"), "además", "STYLE-004e"),
    (re.compile(r"\btambien\b"), "también", "STYLE-004f"),
    (re.compile(r'\bsolo\b(?!\s*["\'])'), "", ""),  # skip: modern usage makes this low-signal
]


# ── Helpers ───────────────────────────────────────────────────────────────────


def strip_code_blocks(text: str) -> list[tuple[int, str]]:
    """Return (line_number, line_text) for prose lines only.

    Skips: YAML frontmatter, fenced code blocks, HTML comments, Hugo shortcode-only lines.
    """
    lines = text.splitlines()
    result: list[tuple[int, str]] = []
    in_code = False
    in_frontmatter = False
    in_html_comment = False
    frontmatter_done = False

    for i, line in enumerate(lines, 1):
        stripped = line.strip()

        # ── frontmatter (first --- block only) ───────────────────────────────
        if i == 1 and stripped == "---":
            in_frontmatter = True
            result.append((i, ""))
            continue
        if in_frontmatter:
            result.append((i, ""))
            if stripped == "---":
                in_frontmatter = False
                frontmatter_done = True
            continue

        # ── HTML comments <!-- ... --> (can span multiple lines) ─────────────
        if not in_html_comment and "<!--" in line:
            in_html_comment = True
        if in_html_comment:
            result.append((i, ""))
            if "-->" in line:
                in_html_comment = False
            continue

        # ── fenced code blocks ````...```` ────────────────────────────────────
        if stripped.startswith("```"):
            in_code = not in_code
            result.append((i, ""))
            continue
        if in_code:
            result.append((i, ""))
            continue

        # ── Hugo shortcode-only lines  {{< ... >}} or {{% ... %}} ────────────
        if re.match(r"^\{\{[<%].*[>%]\}\}\s*$", stripped):
            result.append((i, ""))
            continue

        # ── inline HTML tags at line start (e.g. <div>, </div>) ─────────────
        if re.match(r"^\s*</?[a-zA-Z]", line) and ">" in line:
            result.append((i, ""))
            continue

        result.append((i, line))

    return result


def extract_code_blocks(text: str) -> list[tuple[int, str]]:
    """Return (start_line, block_content) for each fenced code block."""
    blocks = []
    lines = text.splitlines()
    in_code = False
    start = 0
    buf: list[str] = []
    for i, line in enumerate(lines, 1):
        if line.strip().startswith("```"):
            if not in_code:
                in_code = True
                start = i
                buf = []
            else:
                in_code = False
                blocks.append((start, "\n".join(buf)))
        elif in_code:
            buf.append(line)
    return blocks


def _is_prose_continuation_candidate(line: str) -> bool:
    stripped = line.strip()
    if not stripped:
        return False
    if stripped.startswith(("#", "- ", "* ", ">", "|")):
        return False
    if re.match(r"^\d+\.\s", stripped):
        return False
    return True


def _normalize_prose_line(line: str) -> str:
    normalized = re.sub(r"\s+", " ", line.strip())
    return normalized


def build_en_wrapped_compaction_map(
    en_prose_lines: list[tuple[int, str]],
) -> dict[str, tuple[int, int, str, str]]:
    """Build a map of EN two-line wrapped prose to a single normalized line.

    Key: normalized merged text from adjacent EN lines.
    Value: (line1, line2, text1, text2)
    """
    compaction: dict[str, tuple[int, int, str, str]] = {}
    for idx in range(len(en_prose_lines) - 1):
        ln1, t1 = en_prose_lines[idx]
        ln2, t2 = en_prose_lines[idx + 1]
        if not _is_prose_continuation_candidate(t1):
            continue
        if not _is_prose_continuation_candidate(t2):
            continue
        # Require the second line to be indented to reduce accidental matches.
        if not t2.startswith((" ", "\t")):
            continue

        merged = _normalize_prose_line(f"{t1} {t2}")
        if merged:
            compaction.setdefault(merged, (ln1, ln2, t1.rstrip(), t2.rstrip()))
    return compaction


def check_register(prose_lines: list[tuple[int, str]], es_rel: str) -> list[dict]:
    findings = []
    tu_lines: list[tuple[int, str]] = []
    usted_lines: list[tuple[int, str]] = []
    for line_no, line in prose_lines:
        if TU_IMPERATIVES.search(line):
            tu_lines.append((line_no, line.rstrip()))
        if USTED_IMPERATIVES.search(line):
            usted_lines.append((line_no, line.rstrip()))

    if tu_lines and usted_lines:
        # Report on the first occurrence of the minority form
        if len(tu_lines) <= len(usted_lines):
            for ln, lt in tu_lines[:3]:
                findings.append(
                    {
                        "file": es_rel,
                        "line": ln,
                        "line_text": lt,
                        "severity": "warning",
                        "code": "STYLE-002",
                        "message": (
                            "Inconsistencia de registro: se usa forma de «tú» (informal) en esta línea "
                            f"pero el documento usa principalmente «usted» (formal). "
                            f"Ejemplos de usted en líneas: {[l for l, _ in usted_lines[:3]]}."
                        ),
                        "suggestion": "Unificar todo el documento a un solo registro. En k8s-es suele preferirse un tratamiento consistente en toda la página.",
                        **context_window(prose_lines, ln),
                    }
                )
        else:
            for ln, lt in usted_lines[:3]:
                findings.append(
                    {
                        "file": es_rel,
                        "line": ln,
                        "line_text": lt,
                        "severity": "warning",
                        "code": "STYLE-002",
                        "message": (
                            "Inconsistencia de registro: se usa forma de «usted» (formal) en esta línea "
                            f"pero el documento usa principalmente «tú» (informal). "
                            f"Ejemplos de tú en líneas: {[l for l, _ in tu_lines[:3]]}."
                        ),
                        "suggestion": "Unificar todo el documento a un solo registro. En k8s-es suele preferirse un tratamiento consistente en toda la página.",
                        **context_window(prose_lines, ln),
                    }
                )
    return findings


def check_terminology(prose_lines: list[tuple[int, str]], es_rel: str) -> list[dict]:
    findings = []
    # Track which variant has been used per term to detect inconsistency
    term_occurrences: dict[str, list[tuple[int, str]]] = {}

    for canonical, variants, code, severity in TERMINOLOGY_RULES:
        if not variants or not code:
            continue
        canonical_pat = re.compile(r"\b" + re.escape(canonical) + r"\b", re.IGNORECASE)
        variant_pats = [
            (v, re.compile(r"\b" + re.escape(v) + r"\b", re.IGNORECASE))
            for v in variants
        ]

        key = canonical
        term_occurrences[key] = []

        for line_no, line in prose_lines:
            if canonical_pat.search(line):
                term_occurrences[key].append((line_no, "canonical"))
            for variant, pat in variant_pats:
                if pat.search(line):
                    term_occurrences[key].append((line_no, variant))

        seen = term_occurrences[key]
        has_canonical = any(t == "canonical" for _, t in seen)
        has_variant = any(t != "canonical" for _, t in seen)

        # Build a line_no -> line_text lookup from prose_lines for this loop
        prose_map = {ln: lt for ln, lt in prose_lines}

        if has_canonical and has_variant:
            # Mixed usage — flag variant lines
            for line_no, kind in seen:
                if kind != "canonical":
                    findings.append(
                        {
                            "file": es_rel,
                            "line": line_no,
                            "line_text": prose_map.get(line_no, ""),
                            "severity": severity,
                            "code": code,
                            "message": (
                                f"Uso inconsistente de «{kind}»: el documento también usa «{canonical}». "
                                f"Usar «{canonical}» de forma consistente según las guías de estilo de k8s."
                            ),
                            "suggestion": f"Sustituir «{kind}» por «{canonical}» en esta línea y revisar el resto del archivo para mantener la misma terminología.",
                            **context_window(prose_lines, line_no),
                        }
                    )
        elif not has_canonical and has_variant:
            # All variant, no canonical — suggest canonical
            for line_no, kind in seen[:2]:
                findings.append(
                    {
                        "file": es_rel,
                        "line": line_no,
                        "line_text": prose_map.get(line_no, ""),
                        "severity": severity,
                        "code": code,
                        "message": (
                            f"Considerar usar «{canonical}» en lugar de «{kind}» "
                            "según las guías de localización de Kubernetes al español."
                        ),
                        "suggestion": f"Cambiar «{kind}» por «{canonical}» si no existe una razón explícita para conservar el término en inglés.",
                        **context_window(prose_lines, line_no),
                    }
                )
    return findings


def check_untranslated_phrases(
    prose_lines: list[tuple[int, str]], es_rel: str
) -> list[dict]:
    findings = []
    seen_spans: set[tuple[int, str]] = set()
    for line_no, line in prose_lines:
        if not line.strip() or line.strip().startswith(("#", "|", ">")):
            continue
        for m in _ENGLISH_PHRASE.finditer(line):
            phrase = " ".join(m.group(0).split())
            # Skip known k8s API objects that must stay in English
            if any(kw in phrase for kw in KEEP_AS_ENGLISH):
                continue
            # Skip if mostly inside backtick inline code
            before = line[: m.start()]
            if before.count("`") % 2 == 1:
                continue
            # Skip phrases that contain Spanish markers
            if not _looks_english(phrase):
                continue
            dedupe_key = (line_no, phrase.lower())
            if dedupe_key in seen_spans:
                continue
            seen_spans.add(dedupe_key)
            findings.append(
                {
                    "file": es_rel,
                    "line": line_no,
                    "line_text": line.rstrip(),
                    "severity": "warning",
                    "code": "STYLE-001",
                    "message": (
                        f"Posible fragmento en inglés sin traducir: «{phrase[:80]}». "
                        "Verificar si debe traducirse al español."
                    ),
                    "suggestion": (
                        "Traducir la frase al español o dejar solo los términos técnicos que deban permanecer en inglés. "
                        "Si debe quedar literal, marcarla claramente como código, título o nombre propio."
                    ),
                    **context_window(prose_lines, line_no),
                }
            )
    return findings


def check_typography(
    prose_lines: list[tuple[int, str]],
    es_rel: str,
    en_prose_lines: list[tuple[int, str]] | None = None,
    en_rel: str | None = None,
) -> list[dict]:
    findings = []
    en_compaction_map = (
        build_en_wrapped_compaction_map(en_prose_lines) if en_prose_lines else {}
    )
    for line_no, line in prose_lines:
        stripped = line.strip()
        # Skip Markdown table rows/separators — spaces are used for column alignment
        if stripped.startswith("|") or re.match(r"^\|?[-: ]+\|", stripped):
            continue
        # Ignore indentation and trailing markdown line-break spaces.
        # Only flag internal double spaces between non-space characters.
        compact_check = line.rstrip()
        has_internal_double_space = re.search(r"\S  +\S", compact_check) is not None
        if has_internal_double_space:
            normalized_es = _normalize_prose_line(re.sub(r"\s{2,}", " ", compact_check))
            wrap_info = en_compaction_map.get(normalized_es)
            if wrap_info:
                en_line_a, en_line_b, en_text_a, en_text_b = wrap_info
                findings.append(
                    {
                        "file": es_rel,
                        "line": line_no,
                        "line_text": line.rstrip(),
                        "severity": "suggestion",
                        "code": "STYLE-007",
                        "message": (
                            "Posible compresión de salto de línea del original EN: "
                            f"en EN esta oración aparece dividida entre líneas {en_line_a}-{en_line_b}, "
                            "mientras que en ES aparece en una sola línea."
                        ),
                        "suggestion": (
                            "Reescribir el bloque como párrafo alineado con EN. "
                            "Cómo redactarlo: "
                            "1) inicia con la idea principal de la oración EN; "
                            "2) agrega una segunda oración corta con el detalle técnico clave; "
                            "3) cierra con una acción concreta para quien revisa. "
                            "Si el bloque es largo, dividirlo en dos líneas/párrafos siguiendo la misma "
                            "secuencia semántica del original EN."
                        ),
                        "reference_file": en_rel,
                        "reference_line": en_line_a,
                        "reference_context": [
                            {"line": en_line_a, "text": en_text_a},
                            {"line": en_line_b, "text": en_text_b},
                        ],
                        **context_window(prose_lines, line_no),
                    }
                )
            else:
                findings.append(
                    {
                        "file": es_rel,
                        "line": line_no,
                        "line_text": line.rstrip(),
                        "severity": "suggestion",
                        "code": "STYLE-004",
                        "message": "Doble espacio detectado en el texto (no al final de línea). Usar un solo espacio entre palabras.",
                        "suggestion": "Eliminar el espacio duplicado para dejar un único espacio entre palabras.",
                        **context_window(prose_lines, line_no),
                    }
                )
        for pat, suggestion, code in _MISSING_ACCENT:
            if not code:
                continue
            if pat.search(line):
                findings.append(
                    {
                        "file": es_rel,
                        "line": line_no,
                        "line_text": line.rstrip(),
                        "severity": "suggestion",
                        "code": code,
                        "message": (
                            f"Posible tilde faltante. Verificar si la palabra debería escribirse «{suggestion}»."
                        ),
                        "suggestion": f"Revisar la palabra marcada y, si corresponde, reemplazarla por «{suggestion}».",
                        **context_window(prose_lines, line_no),
                    }
                )
    return findings


def check_code_blocks_unchanged(
    es_path: Path, en_path: Path, es_rel: str
) -> list[dict]:
    """Verify that command names in code blocks were not accidentally translated."""
    findings = []
    if not en_path.exists():
        return findings

    es_blocks = extract_code_blocks(
        es_path.read_text(encoding="utf-8", errors="replace")
    )
    en_blocks = extract_code_blocks(
        en_path.read_text(encoding="utf-8", errors="replace")
    )

    # Extract kubectl/kubeadm command lines from EN blocks
    cmd_pattern = re.compile(r"^(kubectl|kubeadm|kubelet|helm|docker|crictl)\s+\S+")
    en_commands: set[str] = set()
    en_commands_by_verb: dict[str, list[tuple[int, str]]] = {}
    en_rel = es_rel.replace("content/es/", "content/en/", 1)
    for start_line, block in en_blocks:
        for line in block.splitlines():
            m = cmd_pattern.match(line.strip())
            if m:
                cmd = line.strip()
                en_commands.add(cmd)
                verb = cmd.split()[0]
                en_commands_by_verb.setdefault(verb, []).append((start_line, cmd))

    for start, block in es_blocks:
        for i, line in enumerate(block.splitlines()):
            stripped = line.strip()
            # If EN had this exact command but ES modified it, flag it
            m = cmd_pattern.match(stripped)
            if m:
                # Check if any EN command shares the same verb but differs
                similar = [
                    ec for ec in en_commands if ec.split()[0] == stripped.split()[0]
                ]
                if similar and stripped not in en_commands:
                    ref_line = None
                    verb = stripped.split()[0]
                    if verb in en_commands_by_verb and en_commands_by_verb[verb]:
                        ref_line = en_commands_by_verb[verb][0][0]
                    # Possibly modified — warn
                    findings.append(
                        {
                            "file": es_rel,
                            "line": start + i,
                            "line_text": line.rstrip(),
                            "severity": "warning",
                            "code": "STYLE-005",
                            "message": (
                                f"Comando modificado en bloque de código: `{stripped[:80]}`. "
                                "Los comandos de kubectl/kubeadm no deben traducirse."
                            ),
                            "suggestion": "Restaurar el comando para que coincida con el bloque de código del original EN, manteniendo intactos los nombres de comandos y flags.",
                            "reference_file": en_rel,
                            "reference_line": ref_line,
                        }
                    )
    return findings


def check_file(es_rel: str, repo: Path) -> tuple[list[dict], str | None]:
    es_path = repo / es_rel
    if not es_path.exists():
        return [], f"File not found: {es_rel}"

    text = es_path.read_text(encoding="utf-8", errors="replace")
    prose_lines = strip_code_blocks(text)
    findings: list[dict] = []
    en_rel = es_rel.replace("content/es/", "content/en/", 1)
    en_path = repo / en_rel
    en_prose_lines: list[tuple[int, str]] = []
    if en_path.exists():
        en_text = en_path.read_text(encoding="utf-8", errors="replace")
        en_prose_lines = strip_code_blocks(en_text)

    try:
        findings += check_register(prose_lines, es_rel)
        findings += check_terminology(prose_lines, es_rel)
        findings += check_untranslated_phrases(prose_lines, es_rel)
        findings += check_typography(
            prose_lines,
            es_rel,
            en_prose_lines=en_prose_lines,
            en_rel=en_rel,
        )

        findings += check_code_blocks_unchanged(es_path, en_path, es_rel)
    except Exception as exc:
        return findings, str(exc)

    return findings, None


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", required=True)
    parser.add_argument("--files", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    repo = Path(args.repo)
    files = [f.strip() for f in args.files.split(",") if f.strip()]

    all_findings: list[dict] = []
    errors: list[list[str]] = []

    for es_rel in files:
        findings, err = check_file(es_rel, repo)
        all_findings.extend(findings)
        if err:
            errors.append([es_rel, err])

    result = {"findings": all_findings, "errors": errors}
    Path(args.out).write_text(json.dumps(result, ensure_ascii=False, indent=2))
    print(f"check_style: {len(all_findings)} finding(s), {len(errors)} error(s)")


if __name__ == "__main__":
    main()
