#!/usr/bin/env -S uv --quiet run --script

# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "asyncclick",
#     "mcp[cli]>=1.8.0",
# ]
# ///
# ::: Code Generated by Copilot [7f5f8ff2-6e8b-4e2a-9f70-1ad5baf7c2d1]. This comment will be removed automatically after the file is saved :::
"""
generate_report.py — produce the final Markdown review report.

Merges findings from check_paragraphs, check_links, and check_style,
groups by file, and writes one table per file with line, severity, and
a comment in Spanish.

Usage:
    python3 generate_report.py
        --paragraphs <json>
        --links      <json>
        --style      <json>
        --pr         <number>
        --repo       <url>
        --out        <path>
"""

import argparse
import json
from collections import defaultdict
from datetime import date
from pathlib import Path

SEV_ORDER = {"error": 0, "warning": 1, "suggestion": 2}
SEV_EMOJI = {"error": "🔴 Error", "warning": "🟡 Aviso", "suggestion": "🔵 Sugerencia"}
SEV_LABEL_ES = {"error": "Error", "warning": "Aviso", "suggestion": "Sugerencia"}


def escape_cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def truncate(text: str, limit: int = 120) -> str:
    if len(text) <= limit:
        return text
    return text[: limit - 1].rstrip() + "…"


def format_context_entry(entry: dict, highlight: bool = False) -> str:
    line_no = entry.get("line", "?")
    text = escape_cell(entry.get("text", "").strip()) or "—"
    prefix = "&gt;" if highlight else "&nbsp;"
    return f"{prefix} {line_no}: <code>{truncate(text, 90)}</code>"


def render_context_cell(finding: dict) -> str:
    parts = []
    for entry in finding.get("context_before", []):
        parts.append(format_context_entry(entry))

    grouped_lines = finding.get("grouped_lines") or [
        {"line": finding.get("line", "?"), "text": finding.get("line_text", "").strip()}
    ]
    for entry in grouped_lines:
        line_no = entry.get("line", "?")
        line_text = escape_cell(entry.get("text", "").strip()) or "—"
        parts.append(f"&gt; {line_no}: <code>{truncate(line_text, 90)}</code>")

    for entry in finding.get("context_after", []):
        parts.append(format_context_entry(entry))

    reference = finding.get("reference_context") or []
    if reference:
        parts.append("<br><strong>EN</strong>")
        for entry in reference:
            highlight = entry.get("line") == finding.get("reference_line")
            parts.append(format_context_entry(entry, highlight=highlight))

    return "<br>".join(parts)


def default_suggestion(finding: dict) -> str:
    code = finding.get("code", "")
    if code == "PARA-002":
        return "Resolver el conflicto y eliminar las marcas de merge."
    if code == "PARA-003":
        return (
            "Completar la sección ES comparándola con el contenido EN. "
            "Cómo redactarlo: 1) abre con el objetivo de la sección; "
            "2) añade 1-2 oraciones con el detalle técnico clave que aparece en EN; "
            "3) cierra con una acción concreta para la persona lectora."
        )
    if code == "PARA-004":
        return (
            "Agregar la sección faltante usando la referencia EN incluida en el reporte. "
            "Cómo redactarlo: escribe un primer párrafo de contexto, luego un párrafo corto "
            "con pasos/criterios técnicos, y termina con una recomendación o validación final."
        )
    if code == "PARA-005":
        return "Validar si la sección extra debe mantenerse o alinearse con EN."
    if code == "PARA-007":
        return (
            "Revisar párrafo a párrafo la sección EN correspondiente y verificar que cada "
            "oración esté traducida. Aplicar saltos de línea semánticos (una cláusula por línea) "
            "en ES para facilitar revisiones futuras y mantener paridad con el EN."
        )
    if code.startswith("LINK-"):
        return "Corregir el destino del enlace o actualizar la ancla para que resuelva correctamente."
    if code == "STYLE-001":
        return "Traducir la frase o dejar solo el término técnico que deba permanecer en inglés."
    if code == "STYLE-002":
        return "Elegir un único registro para toda la página y normalizar la redacción."
    if code.startswith("STYLE-003"):
        return "Aplicar la terminología recomendada de forma consistente en todo el archivo."
    if code.startswith("STYLE-004"):
        return "Aplicar la corrección tipográfica sugerida en la línea marcada."
    if code == "STYLE-007":
        return (
            "Reescribir el párrafo para conservar el orden semántico del EN. "
            "Cómo redactarlo: 1) oración de objetivo; "
            "2) oración de detalle técnico; "
            "3) oración final con acción o validación."
        )
    if code == "STYLE-005":
        return "Restaurar el comando exactamente como aparece en el original EN."
    return "Revisar el comentario y aplicar el ajuste indicado en esta línea."


def load_json(path: str) -> dict:
    try:
        return json.loads(Path(path).read_text())
    except Exception as exc:
        return {"findings": [], "errors": [[path, str(exc)]]}


def group_by_file(findings: list[dict]) -> dict[str, list[dict]]:
    by_file: dict[str, list[dict]] = defaultdict(list)
    for f in findings:
        by_file[f["file"]].append(f)
    return by_file


def severity_counts(findings: list[dict]) -> dict[str, int]:
    counts: dict[str, int] = {"error": 0, "warning": 0, "suggestion": 0}
    for f in findings:
        counts[f.get("severity", "suggestion")] += 1
    return counts


def _mergeable_style_finding(finding: dict) -> bool:
    code = finding.get("code", "")
    return code.startswith("STYLE-") and finding.get("severity") != "error"


def compress_findings_for_display(findings: list[dict]) -> list[dict]:
    if not findings:
        return []

    sorted_findings = sorted(
        findings,
        key=lambda x: (
            x.get("file", ""),
            x.get("line", 0),
            SEV_ORDER.get(x.get("severity", "suggestion"), 99),
            x.get("code", ""),
        ),
    )
    merged: list[dict] = []

    for finding in sorted_findings:
        clone = dict(finding)
        clone.setdefault(
            "grouped_lines",
            [{"line": clone.get("line", "?"), "text": clone.get("line_text", "").strip()}],
        )

        if not merged:
            merged.append(clone)
            continue

        previous = merged[-1]
        previous_end = previous.get("line_end", previous.get("line", 0))
        same_bucket = (
            _mergeable_style_finding(clone)
            and _mergeable_style_finding(previous)
            and previous.get("file") == clone.get("file")
            and previous.get("code") == clone.get("code")
            and previous.get("severity") == clone.get("severity")
            and previous.get("message") == clone.get("message")
            and previous.get("suggestion") == clone.get("suggestion")
            and clone.get("line", 0) - previous_end <= 2
        )

        if same_bucket:
            previous.setdefault(
                "grouped_lines",
                [{"line": previous.get("line", "?"), "text": previous.get("line_text", "").strip()}],
            )
            previous["grouped_lines"].extend(clone.get("grouped_lines", []))
            previous["line_end"] = clone.get("line", previous_end)
            previous["context_after"] = clone.get(
                "context_after", previous.get("context_after", [])
            )
            continue

        merged.append(clone)

    return merged


def line_label(finding: dict) -> str:
    start = finding.get("line", "?")
    end = finding.get("line_end")
    if isinstance(start, int) and isinstance(end, int) and end > start:
        return f"{start}-{end}"
    return str(start)


def build_blob_url(
    repo: str,
    file_path: str,
    line: int | None = None,
    ref: str = "main",
    plain: bool = True,
) -> str:
    base = f"{repo.rstrip('/')}/blob/{ref}/{file_path}"
    if plain:
        base = f"{base}?plain=1"
    if isinstance(line, int) and line > 0:
        return f"{base}#L{line}"
    return base


def summarize_categories(findings: list[dict]) -> list[dict]:
    grouped: dict[tuple, dict] = {}
    for finding in findings:
        category_suggestion = default_suggestion(finding)
        key = (
            finding.get("severity", "suggestion"),
            finding.get("code", ""),
        )
        bucket = grouped.setdefault(
            key,
            {
                "severity": finding.get("severity", "suggestion"),
                "code": finding.get("code", ""),
                "suggestion": category_suggestion,
                "message": finding.get("message", ""),
                "count": 0,
                "files": set(),
                "examples": [],
            },
        )
        bucket["count"] += 1
        bucket["files"].add(finding.get("file", "").split("/")[-1])
        if len(bucket["examples"]) < 3:
            bucket["examples"].append(
                {
                    "file": finding.get("file", "").split("/")[-1],
                    "line": line_label(finding),
                    "line_text": finding.get("line_text", "").strip(),
                }
            )

    return sorted(
        grouped.values(),
        key=lambda item: (
            SEV_ORDER.get(item["severity"], 99),
            -item["count"],
            item["code"],
        ),
    )


def github_line_url(
    repo: str,
    pr: str,
    file_path: str,
    finding: dict,
    head_repo: str = "",
    head_ref: str = "",
) -> str:
    start = finding.get("line", "")
    if not isinstance(start, int):
        return ""
    target_repo = head_repo or repo
    target_ref = head_ref or "main"
    return build_blob_url(target_repo, file_path, start, ref=target_ref)


def render_evidence_cell(finding: dict, repo: str) -> str:
    reference_file = finding.get("reference_file", "")
    reference_line = finding.get("reference_line")
    if isinstance(reference_file, str) and reference_file.startswith("content/en/"):
        en_url = build_blob_url(
            repo,
            reference_file,
            reference_line if isinstance(reference_line, int) and reference_line > 0 else None,
            ref="main",
        )
        line_label = f"L{reference_line}" if isinstance(reference_line, int) and reference_line > 0 else "archivo"
        return f"[EN {line_label}]({en_url})"

    es_file = finding.get("file", "")
    es_line = finding.get("line")
    if isinstance(es_file, str) and es_file.startswith("content/es/"):
        en_file = es_file.replace("content/es/", "content/en/", 1)
        en_url = build_blob_url(repo, en_file, es_line if isinstance(es_line, int) and es_line > 0 else None)
        line_label = f"L{es_line}" if isinstance(es_line, int) and es_line > 0 else "archivo"
        return f"[EN {line_label}]({en_url})"

    return "—"


def render_table(
    findings: list[dict],
    repo: str = "",
    pr: str = "",
    head_repo: str = "",
    head_ref: str = "",
) -> str:
    # Sort by line, then severity
    sorted_f = sorted(
        findings,
        key=lambda x: (
            x.get("line", 0),
            SEV_ORDER.get(x.get("severity", "suggestion"), 99),
        ),
    )
    lines = [
        "| Línea | Código | Severidad | Contexto | Evidencia EN | Comentario | Sugerencia |",
        "|------:|--------|-----------|----------|--------------|------------|------------|",
    ]
    for f in sorted_f:
        label = line_label(f)
        url = (
            github_line_url(
                repo,
                pr,
                f.get("file", ""),
                f,
                head_repo=head_repo,
                head_ref=head_ref,
            )
            if repo and pr
            else ""
        )
        line_cell = f"[{label}]({url})" if url else label
        code = f.get("code", "")
        sev = f.get("severity", "suggestion")
        emoji = SEV_EMOJI.get(sev, sev)
        msg = escape_cell(f.get("message", ""))
        suggestion = escape_cell(f.get("suggestion", "") or default_suggestion(f))
        context_cell = render_context_cell(f)
        evidence_cell = render_evidence_cell(f, repo) if repo else "—"
        lines.append(
            f"| {line_cell} | `{code}` | {emoji} | {context_cell} | {evidence_cell} | {msg} | {suggestion} |"
        )
    return "\n".join(lines)


def render_compact_comment(findings: list[dict], pr: str) -> str:
    counts = severity_counts(findings)
    total = sum(counts.values())
    by_file = group_by_file(findings)
    lines = [
        f"## Revisión rápida PR #{pr}",
        "",
        f"Se detectaron **{total} observaciones**: {counts['error']} errores, {counts['warning']} avisos y {counts['suggestion']} sugerencias.",
        "",
    ]

    blocking = [f for f in findings if f.get("severity") == "error"]
    if blocking:
        lines += ["### Bloqueantes", ""]
        for category in summarize_categories(blocking)[:6]:
            files = ", ".join(sorted(category["files"]))
            count_label = "hallazgo" if category["count"] == 1 else "hallazgos"
            lines.append(
                f"- **`{category['code']}`**: {category['count']} {count_label} en {files}."
            )
            lines.append(f"  Sugerencia: {category['suggestion']}")
            if category["examples"]:
                sample_parts = [
                    f"{sample['file']}:{sample['line']}"
                    for sample in category["examples"]
                ]
                lines.append(f"  Ejemplos: {', '.join(sample_parts)}")
        remaining_categories = max(0, len(summarize_categories(blocking)) - 6)
        if remaining_categories:
            lines.append(
                f"- Hay {remaining_categories} categorías bloqueantes adicionales en el reporte detallado."
            )
        lines.append("")

    lines += ["### Resumen por archivo", ""]
    for file_path in sorted(by_file.keys()):
        file_findings = by_file[file_path]
        file_counts = severity_counts(file_findings)
        file_name = file_path.split("/")[-1]
        lines.append(
            f"- **{file_name}**: {file_counts['error']} errores, {file_counts['warning']} avisos, {file_counts['suggestion']} sugerencias."
        )

    high_signal = [f for f in findings if f.get("severity") in {"error", "warning"}]
    if high_signal:
        lines += ["", "### Observaciones principales", ""]
        for category in summarize_categories(high_signal)[:8]:
            example = category["examples"][0] if category["examples"] else None
            context = example.get("line_text", "") if example else ""
            context_suffix = f" Contexto: `{truncate(context, 70)}`." if context else ""
            sample_ref = (
                f" Ejemplo: {example['file']}:{example['line']}."
                if example
                else ""
            )
            lines.append(
                f"- **`{category['code']}`** — {category['suggestion']}{sample_ref}{context_suffix}"
            )

    return "\n".join(lines).strip() + "\n"


def render_summary_checklist(counts: dict[str, int], files: list[str]) -> str:
    total = sum(counts.values())
    lines = [
        "## Checklist para el autor del PR",
        "",
        f"**Total de observaciones:** {total} "
        f"({counts['error']} errores, {counts['warning']} avisos, {counts['suggestion']} sugerencias)",
        "",
        "### Obligatorio antes del merge",
        "",
    ]
    if counts["error"] == 0:
        lines.append("- [x] Sin errores bloqueantes. ✅")
    else:
        lines.append(
            f"- [ ] Corregir los **{counts['error']} errores** marcados con 🔴 en las tablas de abajo."
        )

    lines += [
        "",
        "### Recomendado",
        "",
        f"- [ ] Revisar los **{counts['warning']} avisos** marcados con 🟡.",
        "",
        "### Opcional",
        "",
        f"- [ ] Considerar las **{counts['suggestion']} sugerencias** marcadas con 🔵.",
        "",
    ]
    return "\n".join(lines)


def render_enumerated_observations(findings: list[dict]) -> str:
    if not findings:
        return ""

    categories = summarize_categories(findings)
    lines = [
        "## Resumen enumerado de observaciones",
        "",
        "Lista priorizada por severidad y volumen:",
        "",
    ]
    for idx, category in enumerate(categories, 1):
        sev = category.get("severity", "suggestion")
        sev_label = SEV_LABEL_ES.get(sev, "Sugerencia")
        files = ", ".join(sorted(category.get("files", [])))
        examples = category.get("examples", [])
        sample = examples[0] if examples else None
        sample_ref = (
            f" Ejemplo: {sample['file']}:{sample['line']}."
            if sample
            else ""
        )
        lines.append(
            f"{idx}. `{category.get('code', '')}` ({sev_label}) — "
            f"{category.get('count', 0)} caso(s) en {files}."
            f" {category.get('suggestion', '')}{sample_ref}"
        )

    lines.append("")
    return "\n".join(lines)


def render_error_section(all_errors: list) -> str:
    if not all_errors:
        return ""
    lines = ["## Errores de análisis", ""]
    for item in all_errors:
        lines.append(f"- `{item[0]}`: {item[1]}")
    lines.append("")
    return "\n".join(lines)


LINE_TOLERANCE = 5  # lines of tolerance when matching previous findings


def _finding_key(f: dict) -> tuple:
    """Canonical match key: (file, code). Line used only for proximity check."""
    return (f.get("file", ""), f.get("code", ""))


def compare_with_base(
    current: list[dict], base: list[dict]
) -> tuple[list[dict], list[dict], list[dict]]:
    """
    Returns (resolved, pending, new_findings).
    A base finding is 'pending' when a current finding shares the same
    (file, code) within LINE_TOLERANCE lines.
    """
    resolved: list[dict] = []
    pending: list[dict] = []
    new_findings: list[dict] = []

    # Build index of current findings by (file, code) -> list of lines
    current_index: dict[tuple, list[int]] = defaultdict(list)
    for cf in current:
        current_index[_finding_key(cf)].append(cf.get("line", 0))

    base_keys_matched: set[int] = set()  # indices of base items matched as pending

    for i, bf in enumerate(base):
        key = _finding_key(bf)
        base_line = bf.get("line", 0)
        if key in current_index:
            # Check line proximity
            near = any(
                abs(cl - base_line) <= LINE_TOLERANCE for cl in current_index[key]
            )
            if near:
                pending.append(bf)
                base_keys_matched.add(i)
                continue
        resolved.append(bf)

    # New findings: current items whose (file, code, approx_line) don't match any base item
    base_index: dict[tuple, list[int]] = defaultdict(list)
    for bf in base:
        base_index[_finding_key(bf)].append(bf.get("line", 0))

    for cf in current:
        key = _finding_key(cf)
        cf_line = cf.get("line", 0)
        if key in base_index:
            near = any(abs(bl - cf_line) <= LINE_TOLERANCE for bl in base_index[key])
            if near:
                continue  # matched to a base finding
        new_findings.append(cf)

    return resolved, pending, new_findings


def render_k8s_contrib_checklist(files: list[str]) -> str:
    return """\
## Checklist de contribución (kubernetes/website)

Según las [guías de revisión de PRs](https://kubernetes.io/docs/contribute/review/reviewing-prs/):

- [ ] Los nombres de comandos (`kubectl`, `kubeadm`, etc.) no fueron modificados
- [ ] Las rutas de archivos y nombres de recursos de la API se mantienen en inglés
- [ ] El frontmatter incluye `title`, `description`, y `weight`
- [ ] No hay marcadores de conflicto de merge (`<<<<`, `====`, `>>>>`)
- [ ] Los bloques de código son correctos y ejecutables
- [ ] El documento mantiene el tono y registro consistente con el resto del sitio

"""


def render_followup_section(
    resolved: list[dict], pending: list[dict], new_findings: list[dict],
    repo: str = "", pr: str = "", head_repo: str = "", head_ref: str = "",
) -> str:
    lines = [
        "## Seguimiento de sugerencias previas",
        "",
        "| Grupo | Cantidad |",
        "|-------|----------|",
        f"| \u2705 Aplicado (resuelto) | {len(resolved)} |",
        f"| \u26a0\ufe0f Pendiente (sin resolver) | {len(pending)} |",
        f"| \U0001f195 Nuevo (no en revisi\u00f3n anterior) | {len(new_findings)} |",
        "",
    ]

    if pending:
        lines += [
            "### \u26a0\ufe0f Observaciones pendientes de la revisi\u00f3n anterior",
            "",
            "| Archivo | L\u00ednea | C\u00f3digo | Severidad | Comentario |",
            "|---------|------:|--------|-----------|------------|",
        ]
        for f in sorted(pending, key=lambda x: (x.get("file", ""), x.get("line", 0))):
            file_short = f.get("file", "").split("/")[-1]
            raw_line = f.get("line", "?")
            url = (
                github_line_url(
                    repo,
                    pr,
                    f.get("file", ""),
                    f,
                    head_repo=head_repo,
                    head_ref=head_ref,
                )
                if repo
                else ""
            )
            line_cell = f"[{raw_line}]({url})" if url else str(raw_line)
            code = f.get("code", "")
            sev = SEV_EMOJI.get(f.get("severity", "suggestion"), "")
            msg = f.get("message", "").replace("|", "\\|").replace("\n", " ")[:120]
            lines.append(f"| `{file_short}` | {line_cell} | `{code}` | {sev} | {msg} |")
        lines.append("")

    if resolved:
        lines += [
            "### \u2705 Observaciones resueltas",
            "",
            "| Archivo | L\u00ednea | C\u00f3digo | Comentario |",
            "|---------|------:|--------|------------|",
        ]
        for f in sorted(resolved, key=lambda x: (x.get("file", ""), x.get("line", 0))):
            file_short = f.get("file", "").split("/")[-1]
            raw_line = f.get("line", "?")
            url = (
                github_line_url(
                    repo,
                    pr,
                    f.get("file", ""),
                    f,
                    head_repo=head_repo,
                    head_ref=head_ref,
                )
                if repo
                else ""
            )
            line_cell = f"[{raw_line}]({url})" if url else str(raw_line)
            code = f.get("code", "")
            msg = f.get("message", "").replace("|", "\\|").replace("\n", " ")[:100]
            lines.append(f"| `{file_short}` | {line_cell} | `{code}` | ~~{msg}~~ |")
        lines.append("")

    lines.append("---")
    lines.append("")
    return "\n".join(lines)

    return """\
## Checklist de contribución (kubernetes/website)

Según las [guías de revisión de PRs](https://kubernetes.io/docs/contribute/review/reviewing-prs/):

- [ ] Los nombres de comandos (`kubectl`, `kubeadm`, etc.) no fueron modificados
- [ ] Las rutas de archivos y nombres de recursos de la API se mantienen en inglés
- [ ] El frontmatter incluye `title`, `description`, y `weight`
- [ ] No hay marcadores de conflicto de merge (`<<<<`, `====`, `>>>>`)
- [ ] Los bloques de código son correctos y ejecutables
- [ ] El documento mantiene el tono y registro consistente con el resto del sitio

"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--paragraphs", required=True)
    parser.add_argument("--links", required=True)
    parser.add_argument("--style", required=True)
    parser.add_argument("--pr", required=True)
    parser.add_argument("--repo", default="https://github.com/kubernetes/website")
    parser.add_argument(
        "--head-repo",
        default="",
        help="PR head repository URL used for Spanish file references",
    )
    parser.add_argument(
        "--head-ref",
        default="",
        help="PR head git ref (typically commit SHA) for Spanish file references",
    )
    parser.add_argument("--out", required=True)
    parser.add_argument(
        "--comment-out",
        default=None,
        metavar="PATH",
        help="Optional path for a compact PR comment Markdown artifact",
    )
    parser.add_argument(
        "--base-findings",
        default=None,
        metavar="PATH",
        help="JSON findings from a previous review for follow-up comparison",
    )
    args = parser.parse_args()

    para_data = load_json(args.paragraphs)
    link_data = load_json(args.links)
    style_data = load_json(args.style)

    all_findings = (
        para_data.get("findings", [])
        + link_data.get("findings", [])
        + style_data.get("findings", [])
    )
    display_findings = compress_findings_for_display(all_findings)
    all_errors = (
        para_data.get("errors", [])
        + link_data.get("errors", [])
        + style_data.get("errors", [])
    )

    by_file = group_by_file(display_findings)
    total_counts = severity_counts(display_findings)
    files_reviewed = sorted(by_file.keys()) or ["(ninguno)"]

    # Follow-up comparison if base findings provided
    followup_section = ""
    if args.base_findings:
        try:
            base_data = json.loads(Path(args.base_findings).read_text())
            base_findings = base_data.get("findings", [])
            resolved, pending, new_findings = compare_with_base(
                display_findings, compress_findings_for_display(base_findings)
            )
            followup_section = render_followup_section(
                resolved,
                pending,
                new_findings,
                args.repo,
                args.pr,
                head_repo=args.head_repo,
                head_ref=args.head_ref,
            )
        except Exception as exc:
            followup_section = (
                f"\n> **Advertencia:** No se pudo cargar el archivo de base: {exc}\n"
            )

    is_followup = bool(followup_section)

    pr_url = f"{args.repo.rstrip('/')}/pull/{args.pr}"
    mode_label = "Seguimiento" if is_followup else "Revisi\u00f3n"

    mode_str = "Seguimiento (con base de revisión anterior)" if is_followup else "Primera revisión"
    lines = [
        f"# {mode_label} de PR #{args.pr} \u2014 Documentaci\u00f3n Kubernetes en Espa\u00f1ol",
        "",
        f"> **PR:** [{pr_url}]({pr_url})  ",
        f"> **Fecha:** {date.today()}  ",
        f"> **Archivos revisados:** {len(files_reviewed)}  ",
        f"> **Modo:** {mode_str}  ",
        "> **Herramienta:** k8s-es-translation-review  ",
        "",
        "---",
        "",
    ]

    if followup_section:
        lines.append(followup_section)

    lines += [
        render_summary_checklist(total_counts, files_reviewed),
        render_enumerated_observations(display_findings),
        render_k8s_contrib_checklist(files_reviewed),
    ]

    if all_errors:
        lines.append(render_error_section(all_errors))

    lines += [
        "---",
        "",
        "## Observaciones por archivo",
        "",
    ]

    if not by_file:
        lines.append(
            "_No se encontraron observaciones. El PR cumple con los criterios de revisión._ ✅\n"
        )
    else:
        for file_path in sorted(by_file.keys()):
            file_findings = by_file[file_path]
            fc = severity_counts(file_findings)
            badge = ""
            if fc["error"]:
                badge = f" — {fc['error']} 🔴"
            elif fc["warning"]:
                badge = f" — {fc['warning']} 🟡"
            else:
                badge = f" — {fc['suggestion']} 🔵"
            if file_path.startswith("content/es/"):
                blob_url = build_blob_url(
                    args.head_repo or args.repo,
                    file_path,
                    ref=args.head_ref or "main",
                )
            else:
                blob_url = build_blob_url(args.repo, file_path, ref="main")
            lines += [
                f"### [`{file_path}`]({blob_url}){badge}",
                "",
                render_table(
                    file_findings,
                    args.repo,
                    args.pr,
                    head_repo=args.head_repo,
                    head_ref=args.head_ref,
                ),
                "",
            ]

    lines += [
        "---",
        "",
        "## Códigos de revisión",
        "",
        "| Código | Descripción |",
        "|--------|-------------|",
        "| PARA-001 | Frontmatter incompleto (campo faltante) |",
        "| PARA-002 | Marcador de conflicto de merge sin resolver |",
        "| PARA-003 | Sección con muy poco contenido respecto al original |",
        "| PARA-004 | Sección h2 del original EN ausente en la traducción |",
        "| PARA-005 | Sección h2 extra en ES sin equivalente EN |",
        "| PARA-006 | Archivo ES huérfano (sin fuente EN) |",
        "| PARA-007 | Compresión de saltos de línea semánticos: ES tiene significativamente menos líneas de prosa que EN |",
        "| LINK-001 | Enlace interno roto |",
        "| LINK-002 | Enlace a ruta ES inexistente (sí existe en EN) |",
        "| LINK-003 | Ancla `#id` no encontrada en archivo destino |",
        "| STYLE-001 | Fragmento en inglés sin traducir (4+ palabras) |",
        "| STYLE-002 | Inconsistencia de registro (tú vs usted) |",
        "| STYLE-003x | Terminología inconsistente |",
        "| STYLE-004x | Error tipográfico (doble espacio, tilde faltante) |",
        "| STYLE-007 | Compresión EN(2 líneas) → ES(1 línea) que puede desalinear contexto |",
        "| STYLE-005 | Comando de kubectl/kubeadm modificado en bloque de código |",
        "",
        "_Generado por [k8s-docs-es-review](https://github.com/kubernetes/website)_",
    ]

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    if args.comment_out:
        comment_path = Path(args.comment_out)
        comment_path.parent.mkdir(parents=True, exist_ok=True)
        comment_path.write_text(
            render_compact_comment(display_findings, args.pr), encoding="utf-8"
        )
        print(
            f"generate_report: compact comment written to {comment_path} ({comment_path.stat().st_size} bytes)"
        )
    print(
        f"generate_report: report written to {out_path} ({out_path.stat().st_size} bytes)"
    )


if __name__ == "__main__":
    main()
