#!/usr/bin/env -S uv --quiet run --script

# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "asyncclick",
#     "mcp[cli]>=1.8.0",
# ]
# ///
# ::: Code Generated by Copilot [5b539fa2-769d-4c47-b6bd-d235aa805ed4]. This comment will be removed automatically after the file is saved :::
"""
k8s-docs-es-review — main orchestrator.

Usage:
    python3 review_pr.py --pr 12345 [--repo URL] [--out PATH] [--keep-tmp]
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
import urllib.request
from datetime import date
from pathlib import Path

REPO_DEFAULT = "https://github.com/kubernetes/website"
GITHUB_API = "https://api.github.com"


def run(
    cmd: list[str], cwd: str | None = None, check: bool = True
) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, check=check)


def clone_and_fetch(repo_url: str, pr_number: int, tmp_dir: str) -> str:
    """Sparse-clone the repo and fetch the PR branch. Returns repo path."""
    repo_path = os.path.join(tmp_dir, "website")
    print(f"[1/4] Cloning {repo_url} (sparse) …", flush=True)
    run(
        [
            "git",
            "clone",
            "--depth",
            "1",
            "--filter=blob:none",
            "--sparse",
            repo_url,
            repo_path,
        ]
    )
    run(["git", "sparse-checkout", "set", "content/en", "content/es"], cwd=repo_path)
    print(f"[1/4] Fetching PR #{pr_number} …", flush=True)
    run(["git", "fetch", "origin", f"pull/{pr_number}/head:pr-branch"], cwd=repo_path)
    run(["git", "checkout", "pr-branch"], cwd=repo_path)
    return repo_path


def get_changed_es_files_from_api(repo_url: str, pr_number: int) -> list[str]:
    """Use GitHub API to list changed content/es/** .md files in the PR."""
    # Derive owner/repo from URL  (https://github.com/owner/repo)
    parts = repo_url.rstrip("/").split("/")
    owner, repo = parts[-2], parts[-1]
    api_url = f"{GITHUB_API}/repos/{owner}/{repo}/pulls/{pr_number}/files?per_page=100"
    req = urllib.request.Request(
        api_url, headers={"Accept": "application/vnd.github+json"}
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            files_data = json.loads(resp.read())
    except Exception as exc:
        print(
            f"  WARNING: GitHub API call failed ({exc}). Falling back to git diff.",
            flush=True,
        )
        return []
    return [
        f["filename"]
        for f in files_data
        if f["filename"].startswith("content/es/") and f["filename"].endswith(".md")
    ]


def get_pr_head_details_from_api(repo_url: str, pr_number: int) -> tuple[str | None, str | None]:
    """Return (head_repo_html_url, head_sha) for the PR, if available."""
    parts = repo_url.rstrip("/").split("/")
    owner, repo = parts[-2], parts[-1]
    api_url = f"{GITHUB_API}/repos/{owner}/{repo}/pulls/{pr_number}"
    req = urllib.request.Request(
        api_url, headers={"Accept": "application/vnd.github+json"}
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            pr_data = json.loads(resp.read())
    except Exception as exc:
        print(
            f"  WARNING: Could not resolve PR head repo/ref from API ({exc}).",
            flush=True,
        )
        return None, None

    head = pr_data.get("head") or {}
    head_repo = (head.get("repo") or {}).get("html_url")
    head_sha = head.get("sha")
    return head_repo, head_sha


def run_script(script: str, args: list[str]) -> subprocess.CompletedProcess:
    """Run a companion script; on failure, write an empty findings JSON to --out."""
    script_path = Path(__file__).parent / script
    cmd = [sys.executable, str(script_path)] + args
    print(f"  → {script}", flush=True)
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(
            f"    WARNING: {script} exited {result.returncode}\n{result.stderr[:800]}",
            flush=True,
        )
        # Write an empty-but-valid JSON so the report generator can continue
        try:
            out_idx = args.index("--out")
            out_path = Path(args[out_idx + 1])
            if not out_path.exists():
                out_path.write_text(
                    json.dumps(
                        {"findings": [], "errors": [[script, result.stderr[:200]]]}
                    )
                )
        except (ValueError, IndexError):
            pass
    return result


def validate_results(paragraphs_out: str, links_out: str, style_out: str) -> list[str]:
    errors = []
    for path, label in [
        (paragraphs_out, "paragraphs"),
        (links_out, "links"),
        (style_out, "style"),
    ]:
        if not os.path.exists(path):
            errors.append(f"Missing output: {label} ({path})")
            continue
        with open(path) as f:
            data = json.load(f)
        if not isinstance(data, dict):
            errors.append(f"Invalid JSON shape in {label}")
    return errors


def main() -> None:
    parser = argparse.ArgumentParser(description="k8s Spanish PR reviewer")
    parser.add_argument("--pr", type=int, required=True, help="GitHub PR number")
    parser.add_argument("--repo", default=REPO_DEFAULT, help="Repository URL")
    parser.add_argument("--out", default=None, help="Output report path")
    parser.add_argument(
        "--comment-out",
        default=None,
        help="Optional output path for a compact PR comment Markdown artifact",
    )
    parser.add_argument(
        "--keep-tmp", action="store_true", help="Keep temp directory after run"
    )
    parser.add_argument(
        "--save-findings",
        default=None,
        metavar="PATH",
        help="Save combined findings JSON for use as --base-findings in a follow-up review",
    )
    parser.add_argument(
        "--base-findings",
        default=None,
        metavar="PATH",
        help="Findings JSON from a previous review; enables follow-up mode",
    )
    args = parser.parse_args()

    out_path = args.out or f"./reports/k8s-review-PR{args.pr}-{date.today()}.md"
    comment_out_path = args.comment_out
    if comment_out_path is None:
        out_path_obj = Path(out_path)
        comment_out_path = str(
            out_path_obj.with_name(f"{out_path_obj.stem}-comment{out_path_obj.suffix}")
        )
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    Path(comment_out_path).parent.mkdir(parents=True, exist_ok=True)

    tmp_dir = tempfile.mkdtemp(prefix="k8s_review_")
    try:
        repo_path = clone_and_fetch(args.repo, args.pr, tmp_dir)
        head_repo, head_ref = get_pr_head_details_from_api(args.repo, args.pr)
        if not head_ref:
            head_ref = run(["git", "rev-parse", "HEAD"], cwd=repo_path).stdout.strip()
        if not head_repo:
            head_repo = args.repo

        print("[2/4] Identifying changed Spanish files …", flush=True)
        changed = get_changed_es_files_from_api(args.repo, args.pr)
        if not changed:
            print(
                "No content/es/** Markdown files changed in this PR. Nothing to review."
            )
            sys.exit(0)

        # Ensure sparse checkout includes all changed ES paths (and their EN mirrors)
        es_dirs = {"/".join(f.split("/")[:-1]) for f in changed}
        en_dirs = {d.replace("content/es/", "content/en/", 1) for d in es_dirs}
        run(
            ["git", "sparse-checkout", "add"] + sorted(es_dirs | en_dirs), cwd=repo_path
        )

        print(f"  Files to review: {len(changed)}")
        for f in changed:
            print(f"    {f}")

        files_arg = ",".join(changed)
        paragraphs_out = os.path.join(tmp_dir, "paragraphs.json")
        links_out = os.path.join(tmp_dir, "links.json")
        style_out = os.path.join(tmp_dir, "style.json")

        print("[3/4] Running checks …", flush=True)
        run_script(
            "check_paragraphs.py",
            [
                "--repo",
                repo_path,
                "--files",
                files_arg,
                "--out",
                paragraphs_out,
            ],
        )
        run_script(
            "check_links.py",
            [
                "--repo",
                repo_path,
                "--files",
                files_arg,
                "--out",
                links_out,
            ],
        )
        run_script(
            "check_style.py",
            [
                "--repo",
                repo_path,
                "--files",
                files_arg,
                "--out",
                style_out,
            ],
        )

        validation_errors = validate_results(paragraphs_out, links_out, style_out)
        if validation_errors:
            print("Quality check failures:")
            for e in validation_errors:
                print(f"  ✗ {e}")
            sys.exit(1)

        print("[4/4] Generating report …", flush=True)
        generate_args = [
            "--paragraphs",
            paragraphs_out,
            "--links",
            links_out,
            "--style",
            style_out,
            "--pr",
            str(args.pr),
            "--repo",
            args.repo,
            "--out",
            out_path,
            "--comment-out",
            comment_out_path,
            "--head-repo",
            head_repo,
            "--head-ref",
            head_ref,
        ]
        if args.base_findings:
            if os.path.exists(args.base_findings):
                generate_args += ["--base-findings", args.base_findings]
            else:
                print(
                    f"  WARNING: --base-findings path not found: {args.base_findings}",
                    flush=True,
                )
        run_script("generate_report.py", generate_args)

        # Optionally persist combined findings for future follow-up review
        if args.save_findings:
            combined = []
            for path in [paragraphs_out, links_out, style_out]:
                if os.path.exists(path):
                    combined.extend(
                        json.loads(Path(path).read_text()).get("findings", [])
                    )
            Path(args.save_findings).parent.mkdir(parents=True, exist_ok=True)
            Path(args.save_findings).write_text(
                json.dumps(
                    {"pr": args.pr, "findings": combined}, ensure_ascii=False, indent=2
                )
            )
            print(f"  Findings saved → {args.save_findings}")

        if not os.path.exists(out_path):
            print("ERROR: report was not created.", file=sys.stderr)
            sys.exit(1)

        report_lines = Path(out_path).read_text().count("\n")
        if report_lines < 30:
            print(
                f"WARNING: report seems too short ({report_lines} lines). Check for errors."
            )

        # ::: Code Generated by Copilot [5b539fa2-769d-4c47-b6bd-d235aa805ed4]. This comment will be removed automatically after the file is saved :::
        abs_out_path = str(Path(out_path).resolve())
        abs_comment_path = str(Path(comment_out_path).resolve())
        print(f"\n✅ Review complete → {out_path}")
        print(f"📄 Absolute report path → {abs_out_path}")
        print(f"💬 Compact PR comment → {comment_out_path}")
        print(f"📝 Absolute compact comment path → {abs_comment_path}")

    except subprocess.CalledProcessError as exc:
        print(f"\nERROR running git command:\n{exc.stderr}", file=sys.stderr)
        sys.exit(1)
    finally:
        if not args.keep_tmp:
            shutil.rmtree(tmp_dir, ignore_errors=True)


if __name__ == "__main__":
    main()
